### ISSUE TITLE
TP2 Ejercicio 5. Determinar el alcance, exactitud y precisión de cada uno de los modelos de sensores de presión que se muestran en el catálogo.

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#21]
# Trabajo Practico N°2

### Determinar el alcance, exactitud y precisión de cada uno de los modelos de sensores de presión que se muestran en el catálogo.

![imagen](https://github.com/user-attachments/assets/07a1726c-ddb2-4717-b33c-44ac6fe0d964)

**Comment by MacarenaAC** [comment]
Se realizo actividad.
