### ISSUE TITLE
TP2 Ejercicio 6. Ejemplifique gráficamente la diferencia entre precisión y exactitud.

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#22]
# Trabajo Practico N°2

### Ejemplifique gráficamente la diferencia entre precisión y exactitud.

![imagen](https://github.com/user-attachments/assets/df1bb68a-ff36-4caa-af8e-0b437805e60a)

**Comment by NicolasBa27** [comment]
Finalizado el "Ejercicio 6".
