### ISSUE TITLE
TP4y5 Ejercicio 1.3 ¿Qué es un sensor generador?

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#40]
# Ejercicio N° 1.3
## ¿Qué es un sensor generador?

**Comment by NicolasBa27** [comment]
[TP 4y5-Ejercicio1.3 - Nicolás Barrionuevo.pdf](https://github.com/user-attachments/files/17167719/TP.4y5-Ejercicio1.3.-.Nicolas.Barrionuevo.pdf)
