### ISSUE TITLE
TP4y5 Ejercicio 1.5 Mencione 5 características del sensor termopar.

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#42]
# Ejercicio N° 1.5
## Mencione 5 características del sensor termopar.

**Comment by NicolasBa27** [comment]
[TP 4y5-Ejercicio1.5 - Nicolás Barrionuevo.pdf](https://github.com/user-attachments/files/17171018/TP.4y5-Ejercicio1.5.-.Nicolas.Barrionuevo.pdf)
