### ISSUE TITLE
TP4y5 Ejercicio 1.8 ¿Qué es un sensor electroquímico?

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#45]
# Ejercicio N° 1.8
## ¿Qué es un sensor electroquímico?

**Comment by diegote7** [comment]
Los sensores electroquímicos son dispositivos capaces de detectar y medir la concentración de ciertas sustancias químicas o gases en un entorno a través de reacciones electroquímicas. Estos dispositivos son ampliamente utilizados en diversas aplicaciones, que van desde el monitoreo ambiental hasta aplicaciones médicas y de seguridad industrial.

**Comment by diegote7** [comment]
se completa tarea
