### ISSUE TITLE
TP4y5 Ejercicio 2.2 Visualizar las salidas en pantalla digital o Monitor serial del IDE ó VsCode

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#47]
# Ejercicio N° 2.2
## Visualizar las salidas en pantalla digital o Monitor serial del IDE ó VsCode

**Comment by FerCbr** [comment]
Se adjuntó captura de pantalla en carpeta presentación
