### ISSUE TITLE
TP7 Ejercicio 1.2 ¿Cómo funcionan las pantallas gigantes de matriz de puntos y cuáles son sus aplicaciones?

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#50]
# Ejercicio N° 1.2
## ¿Cómo funcionan las pantallas gigantes de matriz de puntos y cuáles son sus aplicaciones?

**Comment by diegote7** [comment]
Descripción General
Las pantallas de matriz de puntos, también conocidas como matrices de LEDs, son dispositivos de visualización compuestos por una disposición de píxeles en filas y columnas. Estos píxeles están formados por LEDs individuales o grupos de LEDs RGB (rojo, verde, azul), que pueden encenderse o apagarse para mostrar gráficos, texto e imágenes dinámicas.
Estas pantallas pueden tener aplicaciones en exteriores e interiores, y se utilizan en áreas como publicidad, información pública, paneles de puntuación, y arte digital, entre otras.

**Comment by diegote7** [comment]
se completa tarea
