### ISSUE TITLE
TP7 Ejercicio 1.4 ¿Qué tecnología se podría utilizar para hacer una pantalla gigante táctil?. (SAW)

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#52]
# Ejercicio N° 1.4
## ¿Qué tecnología se podría utilizar para hacer una pantalla gigante táctil?. (SAW)

**Comment by NicolasBa27** [comment]
Tecnología SAW


![caractSAW](https://github.com/user-attachments/assets/99cd3f90-5f45-4468-89e3-8c9986ad6cd4)
![pantallaTactil](https://github.com/user-attachments/assets/af111bb2-5821-44f3-a731-091ac25e951a)
