### ISSUE TITLE
TP7 Ejercicio 1.7 ¿Cómo funcionan los teclados en aplicaciones de IoT?

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#55]
# Ejercicio N° 1.7
## ¿Cómo funcionan los teclados en aplicaciones de IoT?

**Comment by NicolasBa27** [comment]
[TP N°7 Ejercicio 1.7 - Nicolás Barrionuevo.pdf](https://github.com/user-attachments/files/17286568/TP.N.7.Ejercicio.1.7.-.Nicolas.Barrionuevo.pdf)
