### ISSUE TITLE
TP6 Ejercicio 1.2 Explique que es un Sensor Smart de Nivel. ¿Cómo se utilizaría? 

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#58]
# Ejercicio N° 1.2
## Explique que es un Sensor Smart de Nivel. ¿Cómo se utilizaría?

**Comment by diegote7** [comment]
Un Sensor Smart de Nivel es un dispositivo electrónico diseñado para medir la cantidad de un líquido o material en un contenedor o depósito, y transmitir esta información de forma digital a un sistema de control. Estos sensores combinan tecnologías de detección de nivel con capacidades de comunicación y procesamiento, lo que les permite integrarse en sistemas de monitoreo y control inteligente, como redes IoT o plataformas de automatización industrial.

**Comment by diegote7** [comment]
se completa tarea
