### ISSUE TITLE
TP6 Ejercicio 1.3 ¿Qué Protocolos de Comunicaciones utilizaría para conectar este tipo de sensores (Smart)?

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#59]
# Ejercicio N° 1.3

**Comment by NicolasBa27** [comment]
[TP6 - Ejercicio1.3 - Nicolás Barrionuevo.pdf](https://github.com/user-attachments/files/17286413/TP6.-.Ejercicio1.3.-.Nicolas.Barrionuevo.pdf)
