### ISSUE TITLE
TP6 Ejercicio 1.6 ¿Qué es el Protocolo ZigBee? ¿Dónde lo implementaría?

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#62]
# Ejercicio N° 1.6
## ¿Qué es el Protocolo ZigBee? ¿Dónde lo implementaría?

**Comment by NicolasBa27** [comment]
[TP6 - Ejercicio1.6 - Nicolás Barrionuevo.pdf](https://github.com/user-attachments/files/17171139/TP6.-.Ejercicio1.6.-.Nicolas.Barrionuevo.pdf)
