### ISSUE TITLE
TP8 Ejercicio 1.C Sensor de lluvia Resistivo YL-83.

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-SyA-2024/Grupo-N-1#76]
# Implementen una simulación de un Sistema de Riego Inteligente en Wokwi o Proteus, utilizando ESP32 ó ARDUINO con los siguientes sensores y especificaciones:

## C) Sensor de lluvia Resistivo YL-83

**Comment by NicolasBa27** [comment]
Se realiza la prueba/test del Sensor de lluvia Resistivo YL-83.
Perteneciente al TP8 Ejercicio 1.C
![sensor](https://github.com/user-attachments/assets/c9cea9df-0900-4af7-950b-d941fd7576e1)
